import { Platform } from "react-native";

export const colors = {
  COLOR_PRIMARY: "#f96163",
  COLOR_LIGHT: "#fff",
  COLOR_DARK: "#000",
  COLOR_DARK_ALT: "#262626",
};

export const shadow = {
  shadowColor: colors.COLOR_DARK,
  shadowOffset: {
    width: 0,
    height: 4,
  },
  shadowOpacity: 0.1,
  shadowRadius: 7,
  elevation: Platform.OS === "android" ? 2 : 0,
};

export const categories = [
  { id: 1, category: "Lunch" },
  { id: 2, category: "Dinner" },
  { id: 3, category: "Desserts" },
  { id: 4, category: "Salads" },
  { id: 5, category: "Soups" },
  { id: 6, category: "Beverages" },
  { id: 7, category: "Breads" },
  { id: 8, category: "Asian" },
  { id: 9, category: "Snacks" },
  { id: 10, category: "Italian" },
];

export const recipeList = [
  {
    id: "01",
    name: "Tuna Tartare",
    image: require("../../assets/images/tuna.jpeg"),
    rating: "4.2",
    ingredients: ["Fresh Tuna", "Lime Juice", "Red Onion", "Avocado"],
    time: "40 mins",
    difficulty: "Medium",
    calories: "420 cal",
  },
  {
    id: "02",
    name: "Grilled Chicken",
    image: require("../../assets/images/chicken.jpeg"),
    rating: "4.5",
    ingredients: ["Chicken Breast", "Olive Oil", "Garlic", "Rosemary"],
    time: "35 mins",
    difficulty: "Easy",
    calories: "500 cal",
  },
  // {
  //   id: "03",
  //   name: "Pasta Carbonara",
  //   image: require("../assets/images/carbonara.jpeg"),
  //   rating: "4.7",
  //   ingredients: ["Spaghetti", "Pancetta", "Eggs", "Parmesan Cheese"],
  //   time: "30 mins",
  //   difficulty: "Medium",
  //   calories: "600 cal",
  // },
  // {
  //   id: "04",
  //   name: "Beef Stroganoff",
  //   image: require("../assets/images/beef-stroganoff.png"),
  //   rating: "4.6",
  //   ingredients: ["Beef", "Mushrooms", "Onions", "Sour Cream"],
  //   time: "45 mins",
  //   difficulty: "Hard",
  //   calories: "650 cal",
  // },
  // {
  //   id: "05",
  //   name: "Vegetable Stir Fry",
  //   image: require("../assets/images/vegetable-stir-fry.png"),
  //   rating: "4.3",
  //   ingredients: ["Broccoli", "Carrots", "Bell Peppers", "Soy Sauce"],
  //   time: "25 mins",
  //   difficulty: "Easy",
  //   calories: "300 cal",
  // },
  // {
  //   id: "06",
  //   name: "Margherita Pizza",
  //   image: require("../assets/images/margherita-pizza.png"),
  //   rating: "4.8",
  //   ingredients: ["Pizza Dough", "Tomato Sauce", "Mozzarella", "Basil"],
  //   time: "20 mins",
  //   difficulty: "Medium",
  //   calories: "700 cal",
  // },
  // {
  //   id: "07",
  //   name: "Caesar Salad",
  //   image: require("../assets/images/caesar-salad.png"),
  //   rating: "4.4",
  //   ingredients: ["Romaine Lettuce", "Croutons", "Parmesan", "Caesar Dressing"],
  //   time: "15 mins",
  //   difficulty: "Easy",
  //   calories: "320 cal",
  // },
  // {
  //   id: "08",
  //   name: "Shrimp Scampi",
  //   image: require("../assets/images/shrimp-scampi.png"),
  //   rating: "4.9",
  //   ingredients: ["Shrimp", "Garlic", "Butter", "Lemon"],
  //   time: "25 mins",
  //   difficulty: "Medium",
  //   calories: "450 cal",
  // },
  // {
  //   id: "09",
  //   name: "Chocolate Lava Cake",
  //   image: require("../assets/images/lava-cake.png"),
  //   rating: "4.9",
  //   ingredients: ["Dark Chocolate", "Butter", "Eggs", "Flour"],
  //   time: "35 mins",
  //   difficulty: "Hard",
  //   calories: "700 cal",
  // },
  // {
  //   id: "10",
  //   name: "Avocado Toast",
  //   image: require("../assets/images/avocado-toast.png"),
  //   rating: "4.1",
  //   ingredients: ["Avocado", "Bread", "Olive Oil", "Lemon"],
  //   time: "10 mins",
  //   difficulty: "Easy",
  //   calories: "250 cal",
  // },
];
